version: "3.7"
services:
  api-gateway:
    build:
      context: ./api-gateway
      target: final
    ports:
      - 5000:5000
    env_file:
      - ./api-gateway/.env
  api-server:
    build:
      context: ./api-server
      target: final
    ports:
      - 3000:3000
    env_file:
      - ./api-server/.env
