apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: NodePort # Change the type to NodePort
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
