apiVersion: v1
kind: Service
metadata:
  name: video-conversion-server
spec:
  type: NodePort # Change the type to NodePort
  selector:
    app: video-conversion-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
