apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-gateway
spce: 
  replicas: 1
  selector: 
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: video-streaming-server-api-gateway
          ports:
            - containerPort: 8080
          