version: '3.7'
services:
  server:
    build:
      context: .
      target: final
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    ports:
      - 8000:8000
    env_file:
      - .env
