name: Publish Video-Conversion Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: |
          cd video-conversion
          docker build --no-cache --build-arg SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}} . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/video-conversion-v1:latest
      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/video-conversion-v1:latest
